### ISSUE TITLE
Get a pointer to the unknown arguement

### ISSUE THREAD

**Issue by namandixit** [jibsen/parg#4]
As far as I can see, when `parg_getopt_long` returns `?`, there is no way to know which argument(s) it faltered on. This makes giving a good error message impossible, since we can't tell the user which of their argument was unknown. Is their any way to extract this information?

**Comment by jibsen** [comment]
The element that contains the error should be `argv[ps->optind - 1]`.

**Comment by namandixit** [comment]
Thanks, that worked!
